import 'package:flutter/material.dart';

class HomeScreenWidget extends StatefulWidget {
  const HomeScreenWidget({super.key});

  @override
  State<HomeScreenWidget> createState() => _HomeScreenWidgetState();
}

class _HomeScreenWidgetState extends State<HomeScreenWidget> {
  @override
  Widget build(BuildContext context) {
    return const SingleChildScrollView(
      child: Text("HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE END ARRIVES")
    );
  }
}