import 'package:flutter/material.dart';

class HomeScreenWidget extends StatefulWidget {
  const HomeScreenWidget({super.key});

  @override
  State<HomeScreenWidget> createState() => _HomeScreenWidgetState();
}

class _HomeScreenWidgetState extends State<HomeScreenWidget> {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: SingleChildScrollView(
        child: Column(
          children: [
            const Text("Gonzales"),
            Image.asset("lib/assets/Chaldea.webp"),
          ],
        ),
        // Text("HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE HOME IS WHERE THE END ARRIVES")
      ),
    );
  }
}